# Generated by Django 4.1.3 on 2022-11-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='proj.clients')),
                ('users', models.ManyToManyField(editable=False, null=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
