# Generated by Django 4.1.3 on 2022-11-24 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(editable=False, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
